baseURL: https://hungle45.github.io/blog/
languageCode: en-us
title: hungln
theme: PaperMod

params:
  author: "Hung Le"
  disableScrollToTop: false
  defaultTheme: dark

  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowWordCount: false

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog bla bla bla

  # social icons
  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1
    - identifier: "til"
      name: "TIL"
      url: "/til/"
      weight: 2
    - identifier: "archives"
      name: "Archives"
      url: "/archives/"
      weight: 3
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 4
